# https://docs.github.com/en/actions/tutorials/publish-packages/publish-nodejs-packages
# https://bun.sh/docs/cli/publish
name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-bun@v2
        with:
          bun-version: latest
          registry-url: 'https://registry.npmjs.org'
      - run: bun install
      - run: bun publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
